export default {
  BEFORE_LOADING_STATE: 'BEFORE_LOADING_STATE',
  PRELOADING_STATE: 'PRELOADING_STATE',
  LOADING_STATE: 'LOADING_STATE',
  GET_INIT_RESPONSE_STATE: 'GET_INIT_RESPONSE_STATE',
  INIT_STATE: 'INIT_STATE',
  SHOW_GAME_STATE: 'SHOW_GAME_STATE',
  BUILD_GRAPHICS_STATE: 'BUILD_GRAPHICS_STATE',
  RECOVERY_STATE: 'RECOVERY_STATE',



  IDLE_STATE: 'IDLE_STATE',
  GET_SPIN_RESPONSE_STATE: 'GET_SPIN_RESPONSE_STATE',
  GET_RESPIN_RESPONSE_STATE: 'GET_RESPIN_RESPONSE_STATE',
  PRE_SPIN_STATE: 'PRE_SPIN_STATE',
  SPIN_STATE: 'SPIN_STATE',
  STOP_STATE: 'STOP_STATE',
  RESPIN_STATE: 'RESPIN_STATE',
  CLOSE_STATE: 'CLOSE_STATE',
  SHOW_WAYS_STATE: 'SHOW_WAYS_STATE',
  OPEN_MYSTERY_STATE: 'OPEN_MYSTERY_STATE',
  TOTAL_COUNTING_STATE: 'TOTAL_COUNTING_STATE',
  OPEN_WILD_STATE: 'OPEN_WILD_STATE',
  FINAL_STATE: 'FINAL_STATE'
};
